language: java
jdk:
  - openjdk8
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
    - zip -r psycode-webservice *
    - mkdir -p deploy
    - mv psycode-webservice.zip deploy/psycode-webservice.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: psycode-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    edge: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: psycode-build
    key: psycode-webservice.zip
    bundle_type: zip
    application: psycode-webservice
    deployment_group: psycode-webservice-group
    region: ap-northeast-2

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients: gom_55@naver.com
